comment: "ResNet Parameter Set"

ckks_params:
  LogN: 16
  LogQ: [55, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]
  LogP: [61, 61, 61]
  LogScale: 40
  H: 16384
  RingType: standard

boot_params:
  LogP: [61, 61, 61, 61, 61, 61, 61, 61]

orion:
  margin: 2 # >= 1
  embedding_method: hybrid # [hybrid, square]
  backend: lattigo # [lattigo, openfhe, heaan]

  fuse_modules: true
  debug: true

  diags_path: ../data/diagonals.h5 # "path/to/diags" | ""
  keys_path: ../data/keys.h5 # "path/to/keys" | ""
  io_mode: none # "load" | "save" | "none"